version: '2'
services:
  mongodb:
    image: mongo:2.4
    container_name: mongodb
    ports:
     - "27017:27017"
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
     - "5672:5672"
     - "15672:15672"
    environment:
     - RABBITMQ_DEFAULT_USER=test
     - RABBITMQ_DEFAULT_PASS=password
  config:
    image: pschlae/patient-config-service
    container_name: patient-config
    ports:
     - "8888:8888"
    environment:
     - SPRING_PROFILES_ACTIVE=production
    depends_on:
     - mongodb
     - rabbitmq
  discovery:
    image: pschlae/patient-discovery-service
    container_name: patient-discovery
    ports:
     - "8761:8761"
  gateway:
    image: pschlae/patient-gateway-service
    container_name: patient-gateway
    ports:
     - "8080:8080"
    environment:
     - SPRING_PROFILES_ACTIVE=production
    depends_on:
     - discovery
     - config
  price-command-side:
    image: pschlae/patient-command-side:latest
    container_name: patient-cmd-side
    depends_on:
     - mongodb
     - rabbitmq
     - discovery
     - config
    ports:
      - "9000"
    environment:
     - SPRING_PROFILES_ACTIVE=production
  price-query-side:
    image: pschlae/patient-query-side:latest
    container_name: patient-qry-side
    depends_on:
     - rabbitmq
     - discovery
     - config
    ports:
     - "9001"
    environment:
     - SPRING_PROFILES_ACTIVE=production